### ISSUE TITLE
Add 1e stats

### ISSUE THREAD

**Issue by slithy** [slithy/rpg_module#1]
1. Add a 1e option to display 1e stat blocks
2. Update the sample document
3. Create the 1e monster listing

**Comment by non** [comment]
@slithy Hi there!

I just found this project (thanks!) and I was wondering if you hit any roadblocks in implementing 1e stat blocks? If it's just a matter of not having time to work on it, I may take a crack at it.

**Comment by slithy** [comment]
Hi non,

No, no roadblocks, just no-one is pushing me to do it so it's at the back of my queue of things I need to do!

Item (1) on the list above is done, but (2) and (3) still have to be done. If you would like to take a look, please feel free!

**Comment by tunesmith** [comment]
Count this as another vote for implementing 1e stat blocks. :) I've been wanting to write a 1e module for a while and just started using this to sketch it out. I'm downloading it from here rather than CTAN. If you can supply any additional information on how to do (2) or (3) above, maybe I could help.

**Comment by slithy** [comment]
The statblock functionality is done, in principle it works but there are no predefined monster statblocks. So what needs done next is for someone to create a spreadsheet containing all the stats of all monsters in MM, MM2 and FF which I can convert into LaTeX macros.

**Comment by tunesmith** [comment]
That sounds great. I have all three. If you create a google sheet or a spreadsheet attachment with a template of what the columns should be, perhaps with an example, I can slowly plug away at it over time. Sounds relaxing. ;)

**Comment by tunesmith** [comment]
I'm pretty sure I've found the template in the codebase, and I've also found some other excel spreadsheets that have most of the database, will just require some exporting and reordering and them some calculations for thaco and xp/levels in places.

I'm curious what the "Special" column is for? It's not part of special attacks or special defenses.

**Comment by slithy** [comment]
The "Special" column is an abbreviated form of SA/SD for display in monster roster/wandering monster tables. You can see an example in rpg-1e-stats/test.tex. You should be able to compile this to test.pdf which shows all the various display formats.

**Comment by slithy** [comment]
I updated the sample doc to display with 1e stats and created a sample rpg-1e-stats.def with the few monsters in the sample doc.

The stats for these monsters are generated from the spreadsheet rpg-1e-stats/monster_list.csv. Open this file in your favourite spreadsheet program, type CSV, using | as the field separator and no text delimiter. You can then add new monsters and save in the same format.

A few notes on the format:

* Use LaTeX formatting within the fields. For a range of numbers use 2 dashes to get an N-dash, e.g. 1--6.
* % character has to be escaped, "\%"
* For negative numbers use "\minus 2" to typeset a minus sign
* The special sequence "\?" is a breaking slash. It will be typeset as "/" but allows a line break immediately afterwards if necessary.
* The special sequence "\+" is typeset as "+" but with a narrow space either side. You will see that I set HD like "1+1" (no space) but XP as "20\+ 2/hp" (with narrow space).
* The special sequence "\x" is typeset as the multiplication symbol, e.g. "2\x Claws, 1\x Bite"
* The plural column can usually be left blank as it is calculated automatically. You need to specify it for irregular plurals or where the word to be pluralised is not the last word (e.g. man -> men, minion of set -> minions of set)
* The category column can usually be left blank, it is intended for grouping monsters of the same type in new monster listings, e.g. "Dragon" would be the category for "White Dragon", "Gold Dragon", "Red Dragon", etc. as they are all part of the "Dragon" listing.

Hopefully the rest is self-explanatory but let me know if anything is not clear or you have any questions.

**Comment by tunesmith** [comment]
Great, thanks! I did a little work on this. It seems the githubby way to do this is to fork your repo and do the work on my fork.

Can you take a look so far? I did the "A" monsters in MM1. Here's the commit:

https://github.com/tunesmith/rpg_module/commit/5ee9e031f754ef967aad0ec3b45b4116f8c5f06b (note - I fixed the duplicated quotes in MV in the following commit)

I'll try not to bug you with every changeset but it'll be good to check in to start to make sure we have the proper conventions.

Initial notes:

- I split Giant Ant into two monsters since they're so different
- I had them initially listed alphabetically like "Ape, Carnivorous" - let me know if you have strong preferences either way because otherwise I might switch it back to alphabetical.
- Note the odd THACO and AC for Anhkheg - is this ok?
- Some monsters have multiple movement rates like Anhkheg, I'm following the literal MM1 convention here
- Chaotic Evil is spelled out, is that all right
- Some resources have Intelligence with extra numerical info, like "Semi (2-4)" and "Low (5-7)", would you like that if I can add it easily? 
- I'm just sort of eyeballing "Monster Level" by looking at their base xp before adding in HP or Special/Exceptional Abilities, I hope that's accurate

Let me know what you think and if you see any corrections I should make. I'll probably continue with the B's next in MM1, I'll probably use "Beetle, Giant" as a category.

**Comment by slithy** [comment]
Hi, if you plan to commit your changes back into the main repo, you should use a branch rather than a fork. Can you check out my repo and try `git checkout -b tunesmiths_branch`? (I'm not sure if I need to assign permissions so let me know if it doesn't work).

In any case I will copy your changes into the master branch of the repo now and take a look.

**Comment by tunesmith** [comment]
I had earlier tried to create a branch on your repo but got a permission denied when I tried to push the branch, so I probably need to be granted some level of permissions to the repo. I agree that would be better if you can give me access. Then I’ll move my changes to the branch.

**Comment by slithy** [comment]
You should now have permission to push a branch.

But hold on, I'm setting up some conversion and test scripts. After I push that, create a new branch and start from there.

**Comment by slithy** [comment]
OK, the script `convert` takes `monster_list.csv` as input and creates `rpg-1e-stats.def` and `test_all.tex`. This tex file contains all the defined monsters in all display formats, so if you compile it you can use this to check everything looks OK.

Here are my comments on the A monsters:

* Your spreadsheet software is putting quotes around the MV stat, because it contains a single quote (12" etc.). Check if you can set your options to not have the extra quotes. If not, it's not a deal-breaker, I can write an extra script to post-process the spreadsheet to remove them.
* I split "Ape" and "Gorilla" into 2 monster listings with the same stats. I think this makes the most sense for monsters which are the same apart from the name.

> I split Giant Ant into two monsters since they're so different

No problem to do this: in that case put them in the same category (I put "Ant") which enables side-by-side stat listing in the newmonster format.

> I had them initially listed alphabetically like "Ape, Carnivorous" - let me know if you have strong preferences either way because otherwise I might switch it back to alphabetical.

I like it the way you have done it.

> Note the odd THACO and AC for Anhkheg - is this ok?

For AC, the template expects a number, as there is an option to use ascending AC and it does the conversion automatically. Also a long entry here screws with the wandering monster and monster roster listing formats. My compromise for cases like this (Lycanthropes were one in the Basic stats with different AC for human form and animal form) is to put it as as **2\\,(4)**. (\\, is a narrow space)

For HD/THAC0, I put one entry for each HD option, so the module author can insert whichever one he wants. (The XP should really be calculated separately for each HD variant). I also added a default "Ankheg" with the range of stats, but this is really only useful for the "new monster" listing.

> Some monsters have multiple movement rates like Anhkheg, I'm following the literal MM1 convention here

That's perfect.

> Chaotic Evil is spelled out, is that all right

Yes, it will automatically be abbreviated to CE in the appropriate places.

> Some resources have Intelligence with extra numerical info, like "Semi (2-4)" and "Low (5-7)", would you like that if I can add it easily?

That option is only printed in the "new monster" listing so it's not that critical. I would just put it as it is in the MM.

> I'm just sort of eyeballing "Monster Level" by looking at their base xp before adding in HP or Special/Exceptional Abilities, I hope that's accurate.

The Monster Levels are listed in Appendix C of the DMG for MM monsters, but I didn't check if the lists there are exhaustive. The FF and MM2 included this info in the monster listing.

Again this is only used in the "new monster" listing so it's not critical if it's not completely accurate.

**Comment by slithy** [comment]
OK I just pushed. Have a go at building test_all.pdf and let me know if you have any problems.

**Comment by tunesmith** [comment]
Looks like I am still not able to push my local branch to your repo, but I'm sure we can get it figured out, so I'll continue with my local branch on your repo (I'm off the fork now). I'm able to build test_all.pdf ! Continuing with the B's...

**Comment by tunesmith** [comment]
Notes on the B's:

- I broke out the Barracudas by HD as well, assuming the 3 ACs corresponded to the three sizes.
- MM1 has the tiny 1/2 symbol in various places. Should I do anything in particular? I tried dropping in \frac{1}{2} but it cased Latex errors. Fire Beetle is 2 1/2 feet... For now it just says "S (2.5’ long)".  Same issue with warthog. And the brownie has half a hit die. There might have been another occurrence too. 
- Check out the Beholder - you may want to adjust AC and HD (it only listed hit points). Brain mole also only has 1 hit point.
- MM1 kind of broke its own convention with "Giant Boar" so I put it in twice as "giant_boar" and "boar_giant". We can remove one if you'd prefer. I also created boar_warthog since the DMG had that.
- MM1 Bugbear description describes some bugbear variations, but they're not in the DMG either so I left them out
- I finished the B's - the test_all.pdf but some of the alignment looks off in the last couple of pages. 

(I guess you can't see these yet but I'll push up the branch when I can.)

**Comment by slithy** [comment]
HI, I added you as a collaborator, but it still says: "Pending Invite: Awaiting tunesmith’s response". Check your GitHub Notifications. Hopefully if you accept the invite you will be able to push your branch.

To answer your questions:

* I created a macro **\half** for the 1/2 symbol
* For monsters listing hp for HD, I would try and put a HD number that makes sense. e.g. for the Beholder, in Appendix E of DMG, THAC0 is listed as 10/9/8/7, which to me suggests 4 Beholder variants with HD 10, 12, 14 or 16. For Brain Mole I might put 1/2. At least this indicates which line in the table to use for saving throws.
* Giant Boar: I would stick with a single listing and follow the same convention you have used elsewhere. I think it's OK to clean up some of these minor inconsistencies.
* Bugbear: I agree with not adding every variant listed in the description text, otherwise it becomes unmanageable. Authors have the option to add user-defined monsters if they need to.
* I'll take a look at formatting/alignment issues when I can see your updates. Don't worry about it for now.

I will be offline for a couple of days, so I'll catch up with you again on Monday. Happy typing!

**Comment by tunesmith** [comment]
Cool, I added those corrections to the B monsters, and successfully pushed the branch. You can see the corrections in the commit messages. I'll try to get through the C's this weekend. I'm dreading the D's. :-)

**Comment by slithy** [comment]
Hi, I just did a quick check of the Cs. I made a few minor fixes to the spreadsheet so you should pull to merge the changes.

* The single and double quote characters ' and " should not be "smart" quote characters, as LaTeX will do that conversion. It's not a big problem, I can adapt the conversion script to cope with this.
* The \+ macro (used in the XP column for example) should not have a space between the + and the number following.
* The conversion script can't handle blank lines at the moment (I can fix this in future).
* The monsters at the end (Acolyte, Rock Baboon, Pit Viper) are conversions from the Basic rulebook. They are there for the sample module, but they are not "official" AD&D monsters so don't need to be in the AD&D monster list. I deleted them for now, I can make a separate definition just for the sample module. Gnoll I left as it is an AD&D monster.
* The wandering monster/monster roster lists are screwed up as they run over one page. This is a limitation of the tabularx environment I use for those lists. I can fix this in the convert script by adding a break every 30 monsters or whatever. In the meantime if you want to see those lists you could just add the breaks manually in test_all.tex:
```
\end{wanderingmonsters}
\begin{wanderingmonsters}[b]
```
* There are 2 types of slash: / is a normal (non-breaking) slash, and you can use the macro \\? for a breaking slash. This is typeset with the same symbol as normal slash but allows a line break after the slash. For example, flying movement 9'/18' should use a normal slash, as you don't want a line break between 9 and 18. But damage 1–3\\?1–3\\?1–4\\?1–4\\?2–8\\?3–12 should use breaking slash as sometimes there should be a line break in between damage items.
* The above damage line (Chimera) is in any case too long for the wandering monster/monster roster table. You could put the second (short version) of the damage as:
```
2\x1--3/2\x1--4/2--8/3--12
```
... though it's still a bit long. You could shorten it a bit more to:
```
2\x1d3/2\x1d4/2d4/3d4
```
though this breaks the convention. I don't know if you have any better ideas.

**Comment by tunesmith** [comment]
That sounds good, I can make those other changes... lemme know if you have a rule of thumb for string length for the "short damage" column, like 20 characters or something. Since that field is not in the MM itself it looks like we can be flexible on convention. 

Also, tell me if there's a rule of thumb in terms of length for when I should consider using non-breaking slash instead of breaking slash. Maybe anything more than three attacks?

Oh also, the wandering monster tables look cut off on the right margin. But maybe that's because of the length thing. I'll play around.

**Comment by slithy** [comment]
> Also, tell me if there's a rule of thumb in terms of length for when I should consider using non- breaking slash instead of breaking slash. Maybe anything more than three attacks?

Best to always to use non-breaking slash in the damage column. In the inline format, you don't know in advance where the line break will fall.

On the other hand, never use it in the MV column as you don't want a line break between the first and second part of the movement rate.

I've updated the `convert` script to better handle the lists at the end. Now it puts in a break after 30 items so everything appears on the same page.

Some stats which are very wide can throw off the table formatting. The convert script now excludes the generic Beholder listing as that is really only useful for the newmonster format and the multiple THAC0s make it too wide to display in a table. Same for generic Wild Cattle.

Some other entries were too wide: Black Pudding had number appearing "1 to 1--4" which I replaced with "1--4". Bulette had "1--2 (10% chance)" which I replaced with "1--2". Brain Mole HD I replaced with 1/8.

Creatures which can have multiple alignments, put them as "Neutral". The `\changealignment` macro can be used by the module author to set a specific alignment.

With those changes, the tables display within the width of a page.

You could abbreviate the "Special" column further in some cases. I would separate "Special" items with semicolons and use lower case apart from the first letter. Abbreviate listings like "Surprise on a 1--3" to "Surprise on 1--3". Remove "See description". etc.

Chimera short form damage is still a bit too long for the table format...

**Comment by tunesmith** [comment]
Ok, I added some more of those corrections. I was able to shorten Chimera a tiny bit more but not much. Only other thing I could think of was something like 2:d4 for 1--4/1--4 but that gets a little more confusing.

I remove See description from demogorgon but now demogorgon is huge :) 

Maybe some font sizing or adjustbox for when the table has a lot of stuff in it?

I add the beginnings of a doc that has a lot of these conventions in cases it helps anyone else that might jump in.

I'll work more on the D's this week.

**Comment by slithy** [comment]
I came up with a simple solution for the monster lists: I reduced the font size to `\small` in the sample document.

For the short damage format, we should have one format for damage dice that we use consistently. I think with the smaller font size, the 1--4 format is OK.

Plus signs: use normal + where you don't want a space or a line break, e.g. `+2 weapon to hit`. Use `\+` where + is connecting two items and there should be a small space either side, e.g. XP `35\+3/hp`.

`Special` column for tables: you could rephrase some SA and SD items to make them shorter, e.g. abbreviate `+2 or better weapon to hit` to `+2 weapon to hit`; `Save as 9th level cleric` could become `Save as Cleric 9`, etc.

**Comment by tunesmith** [comment]
Devils, Demons, Dinosaurs and more are all added. Still have to add Dragons. I keep having to make judgment calls (and correcting DMG errors in some cases) so it might be worth looking at the output again so far. War Dogs wandering monster looks funny, maybe because the MM had "--" for number appearing.

**Comment by slithy** [comment]
Nice work!

I put Chimera in a table on its own and reduced the number of items per table to 20 to get a better display.

For Demons/Devils, "Manes", "Succubus", etc. are fine on their own, but "Type I", "Bone", "Ice", etc. need the Demon/Devil in the name: "Type I Demon", "Bone Devil", etc.

The number appearing field is parsed so it needs to be a number or a range. I put 1-4 for War Dog. In the end this is used as a default range in the wandering monster table which can be overridden by the author so any sensible value is fine.

**Comment by slithy** [comment]
Do you want to point me to the spreadsheets you are working from? I could probably do some pre-processing on them to make this process less manual, so it's checking and correcting rather than entering each line.

**Comment by tunesmith** [comment]
Haven't forgotten about you; summertime. I'm working on dragons now. For each of the dragons that aren't chromatic or platinum, I'll create the three variants; small, average, and huge.

I'd sort of like an additional optional column at the end where I can record the number of SAXPB and EAXPA. For instance, I know that the red dragon has 4 and 3 respectively, thanks to page 85 of the DMG. But compared to that, I'm pretty sure that the black dragon has 2 and 2. If I can record a '2,2' after the last column it'll give a clue as to how the xp calculation is done. I guess it doesn't really make sense to have that column there if it's not going to be in the output but it helps visually... do you think that can be added?

By the way, the monster spreadsheet I found is SBLaxman's AD&D Monster List 2.1, attached. I'm actually finding it faster just to do the data entry because there are some general differences in how monsters are grouped, but maybe you can find more pre-processing patterns.

[SBLaxman's AD&D Monster List 2.1.xlsx](https://github.com/slithy/rpg_module/files/4861887/SBLaxman.s.AD.D.Monster.List.2.1.xlsx)

**Comment by tunesmith** [comment]
Just ignoring that I was dormant on this issue for two years, I pushed a commit to finish the "D" monsters.

**Comment by verdammelt** [comment]
Just wanted to say *Thanks* for doing this. Starting to use this document class for my campaign notes and the stat blocks are really nice to have.

I'll be needing to add a few monsters here and there that haven't been gotten to you (i.e. kobolds, orcs etc) Is it OK for me to put up a PR after I add a few or would that cause problems?

Also for monsters in FF or MM2 do you think you'll just add them to the same monsters list or create new data files for those?

**Comment by slithy** [comment]
Glad you are enjoying rpg-module! The plan is eventually to add all monsters in FF and MM2 but as you can see it's progressing slowly...

If you want to contribute it would be useful if you could do all the monsters for a given letter (K or O maybe...) rather than submit individual monster stats.

**Comment by tunesmith** [comment]
Believe it or not, I added orcs and giant rats last night because of an Appendix A dungeon I'm playing with. :) I just pushed up those two additional lines.

**Comment by tunesmith** [comment]
I've honestly been tempted to switch gears and do something like add the first two columns for all remaining monsters in MM, and then go column by column to see if it's faster for data entry. I'm experimenting with that approach right now with the 'E' letters. But even that can bog down due to the judgment calls that come up (I decided to create `elephant`, `elephant_asiatic`, `elephant_african`, and `loxodont` for the Elephant category).

At any rate, while I've used git for work, I'm less familiar with this forking style. @verdammelt I'd normally be ok with you just making commits to my branch, but I guess the github way would be to open PRs against my branch? I think if you want to pick a letter or even just jump around, that'd be fine, if it conflicts with anything I have in progress I can just deal with it on the merge.

As for FF/MM2, @slithy are you ok with those being separate csv files?

**Comment by tunesmith** [comment]
Hrm, I forgot that I'm not on a fork, but on a branch that @slithy set up. So either is fine for me. If slithy gives you the same level of access to the branch, I'm ok with just always pulling before I start to do more work, with us just making commits to the same branch.

**Comment by slithy** [comment]
Yes, makes sense to have FF and MM2 as separate .csv files.

**Comment by tunesmith** [comment]
By the way, one of the more time-consuming parts of this is figuring out how the xp values correspond to special and exceptional abilities. This is necessary to reverse engineer sometimes so accurate values can be figured for monsters with varying hit dice. I was going through them one by one, but recently I found that someone else had done an exhaustive analysis of every monster in MM, it was on some discussion board somewhere. I don't know enough about licensing to know whether it can be committed to the codebase, but here it is attached for reference.

[dismembering_the_monster_manual_xp_v.4.pdf](https://github.com/slithy/rpg_module/files/8310073/dismembering_the_monster_manual_xp_v.4.pdf)

I haven't double-checked it against the other values I've added (for the monsters up through D).

**Comment by verdammelt** [comment]
@tunesmith Giving me access to this branch is riskier than letting me submit a PR. It is more work though (since it will need to be reviewed etc).

General git workflow (not just GitHub) is to submit a "request to pull" changes from a contributors branch into the main repository. That lets the maintainers control the addition of changes and do some quality control etc.

I'm happy to only submit pull requests when I have an entire letter complete if that works best.

The first thing I'll need to figure out is why I cannot seem to build the `test-all.pdf` file... currently it fails at baboon with an error as if the key wasn't defined. Which is odd - that animal is definitely in there. Hmmm.

Thanks for all your work and I'll keep updating my clone of this repository so when I do create a pull request it will hopefully go smoothly.

**Comment by tunesmith** [comment]
Sounds good. I'm actively working on 'E' so any other letter should be fine. I think I'm about to add Goblin and Gnome too.

**Comment by tunesmith** [comment]
By the way, if it's a pgfkeys error you're experiencing, I have seen that too. I think it's because there's a test file with some content that assumes basic even if you have 1e turned on. I'm able to `make` within the `rpg-1e-stats` folder, though, and it generates `test_all.pdf` in the same folder.

I've tried different workflows. What I'm doing now is opening `monster_list.csv` in OpenOffice so I can freeze the first row/column. I had to change some settings so it wouldn't create smart quotes. Then for a letter, I usually input the data in DMG first (from page 196 on). Then when that's done I go back to the Monster Manual and start filling in the rest. Then I do `./convert` and `make` to see the output in the pdf file.

Thanks for pitching in!

**Comment by tunesmith** [comment]
I just pushed up a first cut at the 'E' monsters.

**Comment by tunesmith** [comment]
Merged PR #5 into this branch.

**Comment by tunesmith** [comment]
I've added gnomes, hobgoblins, kobolds, ghasts, and ghouls recently. Skipping around for now as I use the tool to build my own modules. (Currently rewriting parts of A1 for my own purposes :) )

**Comment by verdammelt** [comment]
I should push up a PR for a few things I've been using recently for my game. giant frog, piercer, skeleton, zombie, brigand, bandit, berserker as well as some FF & MM2 items

**Comment by tunesmith** [comment]
That'd be cool if you were to create separate ff.csv and mm2.csv files and add support for them to the Makefile. I have a giant sundew I could add to mm2. 

(I also just added wight)

**Comment by verdammelt** [comment]
That *would* be cool. Now let's see if I can *do* it :(

**Comment by verdammelt** [comment]
@tunsmith / @slithy - please see PR #6 which allows for space for us to start adding non-MM 1e monsters. Each of the books will have their own file. They are then concatenated during the build before converting to the `.def` file.

Also, I wonder if it might be a good time to merge the 1e-monsters branch into master? That is, perhaps it is good time to declare it "done enough" for public consumption (even though it does not have all 1e monsters yet).

**Comment by slithy** [comment]
Hi, thanks for all the work on this, good to see it advancing! Sorry for being quiet, I am crazy busy at the moment with work commitments etc. but I have been following what you have been doing. I will try to find some time to check and merge into master in the next few weeks!

**Comment by tunesmith** [comment]
Awesome! In the meantime I will take a look at PR #6 soon to merge it into this branch. 

I am fine with merging 1e-monsters into master if the changes look good to @slithy, we can PR chunks of monsters into master after that point.

**Comment by tunesmith** [comment]
I merged PR #6 and added harpies.

**Comment by verdammelt** [comment]
A question for you both about quotes, like in MV column. Should it be `12"` or `12''`? Looks like LaTeX is OK with either?

**Comment by tunesmith** [comment]
So far I've always been using the double-quote character `"`. Not sure though - @slithy let us know if we should change it to `''`? 

Pushed gray ooze and rot grubs.

**Comment by slithy** [comment]
Typographically, they are the same in LaTeX. If you have used `"` up to now, best to be consistent and just stick with that.

**Comment by verdammelt** [comment]
Cool, I'll keep to that.

**Comment by verdammelt** [comment]
@tunesmith this is amazing! 

I don't actually use this project anymore - but would be definitely a consumer of the *data* it contains.

I'd suggest merging the branch and then branching off again for ff and/or mm2 - this branch is way too old as it is!

**Comment by tunesmith** [comment]
Okay, great. I will merge the PR and close the issue. It'll be available as reference for future issue/PR anyway. :)

**Comment by tunesmith** [comment]
Closing under the understanding this was for MM1; future issues/PRs can be for ff or MM2 when desired.
